#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: mublomall-third-party
#
spring:
  redis:
    host: 192.168.56.10
    port: 6379
#    redis的密码
#    password:
