spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mublomall-search
#  elasticsearch:
#    rest:
#      uris: ["192.168.56.10:9200"]
#      connection-timeout: 100000s
  thymeleaf:
    cache: false
server:
  port: 13000
#management:
#  endpoints:
#    web:
#      exposure:
#        include: ['*']
#  health:
#    elasticsearch:
#      response-timeout: 3s

