#yuyanjia:
#  filter:
#    cors:
#      allowed-origin-list:
#        - '*'
#      allowed-header-list:
#        - '*'
#      allowed-method-list:
#        - POST
#        - GET
#        - OPTION
#      exposed-header-list:
#        - access-control-allow-headers
#        - access-control-allow-methods
#        - access-control-allow-origin
#        - access-control-max-age
#        - X-Frame-Options
#      mapping: /website/**